// app/layout.js
import { ThemeProvider } from 'next-themes';
import './globals.css'; // pastikan path CSS Anda benar

// Impor font jika Anda menggunakannya di sini
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="id" suppressHydrationWarning> {/* Penting: suppressHydrationWarning */}
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}